# Enable display system
CONFIG_ZMK_DISPLAY=y

# Required Zephyr display support
CONFIG_DISPLAY=y
CONFIG_DISPLAY_LOG_LEVEL_ERR=y

# SSD1306 driver
CONFIG_SSD1306=y

# I2C must be enabled
CONFIG_I2C=y

# ZMK split central (dongle)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# USB + BLE
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_CENTRAL=y