# CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
# CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n
# CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_NICE_OLED_CUSTOM_CANVAS_WIDTH=128
# CONFIG_NICE_OLED_CUSTOM_CANVAS_HEIGHT=32
